version: '3.8'

services:
    rstudio:
        image: jlaria/glasp:0.0.1
        ports:
            - "8787:8787"
        tty: true
        volumes: 
            - .:/workspace:cached
        command: /bin/sh -c "while sleep 1000; do :; done"
